auto run migration on push"

diff --git a/ci/cloudbuild.yaml b/ci/cloudbuild.yaml
--- a/ci/cloudbuild.yaml
+++ b/ci/cloudbuild.yaml
@@ -15,4 +15,17 @@ steps:
   entrypoint: 'bash'
   args: ['-c', 'gcloud config set app/cloud_build_timeout 3600 && gcloud app deploy -q --promote -v=$BUILD_ID --project=$PROJECT_ID']
 
+- name: 'gcr.io/cloud-builders/gcloud'
+  entrypoint: "bash"
+  args:
+    - "-c"
+    - RESPONSE=$(curl -o /dev/null -s -w "%{http_code}" \
+                      -d "" -X POST $_APP_BASE_URL)
+      if [ "200" != "$$RESPONSE" ];
+      then
+          echo "FAIL: migrations failed" exit 1;
+      else
+          echo "PASS: migrations ran successfully"
+      fi
+
 timeout: '3600s'
