migrate bug

diff --git a/ci/cloudbuild.yaml b/ci/cloudbuild.yaml
--- a/ci/cloudbuild.yaml
+++ b/ci/cloudbuild.yaml
@@ -19,13 +19,13 @@ steps:
   entrypoint: "bash"
   args:
     - "-c"
-    # - RESPONSE=$(curl -o /dev/null -s -w "%{http_code}" -d "" -X POST $_APP_BASE_URL);
-    #   if ["200" != "$$RESPONSE"]; then 
-    #       echo "FAIL migrations failed"
-    #       exit 1;
-    #   else
-    #       echo "PASS migrations ran successfully"
-    #   fi
-    - php artisan migrate
+    - |
+      RESPONSE=$(curl -o /dev/null -s -w "%{http_code}" -d "" -X POST $_APP_BASE_URL);
+      if ["200" != "$$RESPONSE"]; then 
+          echo "FAIL migrations failed"
+          exit 1;
+      else
+          echo "PASS migrations ran successfully"
+      fi
 
 timeout: '3600s'
