auto run migration on push

diff --git a/ci/cloudbuild.yaml b/ci/cloudbuild.yaml
--- a/ci/cloudbuild.yaml
+++ b/ci/cloudbuild.yaml
@@ -22,7 +22,8 @@ steps:
     - RESPONSE=$(curl -o /dev/null -s -w "%{http_code}" -d "" -X POST $_APP_BASE_URL)
       if [ "200" != "$$RESPONSE" ];
       then
-          echo "FAIL: migrations failed" exit 1;
+          echo "FAIL: migrations failed" 
+          exit 1
       else
           echo "PASS: migrations ran successfully"
       fi
